PUSH_GATE 0 Johnson
PUSH_GATE 0 Person_09
PUSH_GATE 1 Person_10
PUSH_GATE 1 Person_11
PUSH_GATE 1 Person_12
PUSH_GATE 1 Dahyun
PUSH_GATE 2 Chaeyoung
PUSH_GATE 2 Person_13
PUSH_GATE 2 Person_14
PUSH_GATE 3 Nayeon
PUSH_GATE 3 Person_06
PUSH_GATE 4 Jihyo
PUSH_GATE 4 Person_17
PUSH_GATE 5 Sana
PUSH_GATE 5 Person_15
PUSH_GATE 6 Tzuyu
PUSH_GATE 6 Person_18
PUSH_GATE 7 Taylor
PUSH_GATE 7 Person_19
PUSH_GATE 8 Person_07
PUSH_GATE 8 Person_20
PUSH_GATE 9 Person_08
PUSH_GATE 9 Person_16
PRINT_GATE 1
POP_GATE 1
PRINT_GATE 2
PRINT_GATE 3
POP_GATE 2
POP_GATE 3
POP_GATE 4
POP_GATE 5
POP_GATE 6
POP_GATE 7
POP_GATE 8
POP_GATE 9
PRINT_GATE 4
PRINT_GATE 5
PRINT_GATE 6
PRINT_GATE 7
PRINT_GATE 8
PRINT_GATE 9
PUSH_PLANE 0 Johnson
PUSH_PLANE 0 Person_09
PUSH_PLANE 1 Person_10
PUSH_PLANE 1 Person_11
PUSH_PLANE 1 Person_12
PUSH_PLANE 1 Dahyun
PUSH_PLANE 2 Chaeyoung
PUSH_PLANE 2 Person_13
PUSH_PLANE 2 Person_14
PUSH_PLANE 3 Nayeon
PUSH_PLANE 3 Person_06
PUSH_PLANE 4 Jihyo
PUSH_PLANE 4 Person_17
PUSH_PLANE 5 Sana
PUSH_PLANE 5 Person_15
PUSH_PLANE 6 Tzuyu
PUSH_PLANE 6 Person_18
PUSH_PLANE 7 Taylor
PUSH_PLANE 7 Person_19
PUSH_PLANE 8 Person_07
PUSH_PLANE 8 Person_20
PUSH_PLANE 9 Person_08
PUSH_PLANE 9 Person_16
PRINT_PLANE 1
POP_PLANE 1
PRINT_PLANE 2
PRINT_PLANE 3
POP_PLANE 2
POP_PLANE 3
POP_PLANE 4
POP_PLANE 5
POP_PLANE 6
POP_PLANE 7
POP_PLANE 8
POP_PLANE 9
PRINT_PLANE 4
PRINT_PLANE 5
PRINT_PLANE 6
PRINT_PLANE 7
PRINT_PLANE 8
PRINT_PLANE 9
QUIT
