Adding luggage of Johnson to GATE 0
Adding luggage of Person_09 to GATE 0
Adding luggage of Person_10 to GATE 1
Adding luggage of Person_11 to GATE 1
Adding luggage of Person_12 to GATE 1
Adding luggage of Dahyun to GATE 1
Adding luggage of Chaeyoung to GATE 2
Adding luggage of Person_13 to GATE 2
Adding luggage of Person_14 to GATE 2
Adding luggage of Nayeon to GATE 3
Adding luggage of Person_06 to GATE 3
Adding luggage of Jihyo to GATE 4
Adding luggage of Person_17 to GATE 4
Adding luggage of Sana to GATE 5
Adding luggage of Person_15 to GATE 5
Adding luggage of Tzuyu to GATE 6
Adding luggage of Person_18 to GATE 6
Adding luggage of Taylor to GATE 7
Adding luggage of Person_19 to GATE 7
Adding luggage of Person_07 to GATE 8
Adding luggage of Person_20 to GATE 8
Adding luggage of Person_08 to GATE 9
Adding luggage of Person_16 to GATE 9
Printing the top luggage of GATE 1
Removing luggage of Dahyun from GATE 1
Printing the top luggage of GATE 2
Printing the top luggage of GATE 3
Removing luggage of Person_14 from GATE 2
Removing luggage of Person_06 from GATE 3
Removing luggage of Person_17 from GATE 4
Removing luggage of Person_15 from GATE 5
Removing luggage of Person_18 from GATE 6
Removing luggage of Person_19 from GATE 7
Removing luggage of Person_20 from GATE 8
Removing luggage of Person_16 from GATE 9
Printing the top luggage of GATE 4
Printing the top luggage of GATE 5
Printing the top luggage of GATE 6
Printing the top luggage of GATE 7
Printing the top luggage of GATE 8
Printing the top luggage of GATE 9
Adding luggage of Johnson to PLANE 0
Adding luggage of Person_09 to PLANE 0
Adding luggage of Person_10 to PLANE 1
Adding luggage of Person_11 to PLANE 1
Adding luggage of Person_12 to PLANE 1
Adding luggage of Dahyun to PLANE 1
Adding luggage of Chaeyoung to PLANE 2
Adding luggage of Person_13 to PLANE 2
Adding luggage of Person_14 to PLANE 2
Adding luggage of Nayeon to PLANE 3
Adding luggage of Person_06 to PLANE 3
Adding luggage of Jihyo to PLANE 4
Adding luggage of Person_17 to PLANE 4
Adding luggage of Sana to PLANE 5
Adding luggage of Person_15 to PLANE 5
Adding luggage of Tzuyu to PLANE 6
Adding luggage of Person_18 to PLANE 6
Adding luggage of Taylor to PLANE 7
Adding luggage of Person_19 to PLANE 7
Adding luggage of Person_07 to PLANE 8
Adding luggage of Person_20 to PLANE 8
Adding luggage of Person_08 to PLANE 9
Adding luggage of Person_16 to PLANE 9
Printing the top luggage of GATE 1
Removing luggage of Dahyun from PLANE 1
Printing the top luggage of GATE 2
Printing the top luggage of GATE 3
Removing luggage of Person_14 from PLANE 2
Removing luggage of Person_06 from PLANE 3
Removing luggage of Person_17 from PLANE 4
Removing luggage of Person_15 from PLANE 5
Removing luggage of Person_18 from PLANE 6
Removing luggage of Person_19 from PLANE 7
Removing luggage of Person_20 from PLANE 8
Removing luggage of Person_16 from PLANE 9
Printing the top luggage of GATE 4
Printing the top luggage of GATE 5
Printing the top luggage of GATE 6
Printing the top luggage of GATE 7
Printing the top luggage of GATE 8
Printing the top luggage of GATE 9
QUIT
